---
  environment: production
  chdir: /home/injekt/code/ramaze-proto
  address: 127.0.0.1
  user: injekt
  group: users
  port: 7000
  pid: /home/injekt/code/ramaze-proto/thin.pid
  rackup: /home/injekt/code/ramaze-proto/config.ru
  log: /home/injekt/code/ramaze-proto/thin.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 512
  daemonize: true
